### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by vil02** [OpenElements/hedera-enterprise#32]
These classes:

- [`FileClientTests`](https://github.com/OpenElements/hedera-enterprise/tree/0ec8cb2222711fdf0077420a3f605a613c095ca2/hedera-microprofile/src/test/java/com/openelements/hedera/microprofile/test/FileClientTests.java),
- [`MirrorNodeClient`](https://github.com/OpenElements/hedera-enterprise/tree/0ec8cb2222711fdf0077420a3f605a613c095ca2/hedera-base/src/main/java/com/openelements/hedera/base/mirrornode/MirrorNodeClient.java),
- [`NftClient`](https://github.com/OpenElements/hedera-enterprise/tree/0ec8cb2222711fdf0077420a3f605a613c095ca2/hedera-base/src/main/java/com/openelements/hedera/base/NftClient.java),
- [`NftRepositoryImpl`](https://github.com/OpenElements/hedera-enterprise/tree/0ec8cb2222711fdf0077420a3f605a613c095ca2/hedera-base/src/main/java/com/openelements/hedera/base/implementation/NftRepositoryImpl.java),
- [`NftRepository`](https://github.com/OpenElements/hedera-enterprise/tree/0ec8cb2222711fdf0077420a3f605a613c095ca2/hedera-base/src/main/java/com/openelements/hedera/base/NftRepository.java),

have some unused imports. I would like to remove them.

**Comment by Ariho-Seth** [comment]
Hello @vil02 Can I Work on this ?

**Comment by vil02** [comment]
> Hello @vil02 Can I Work on this ?

@Ariho-Seth: I am not a maintainer of this repository. I created this issue, because I wanted to remove these unused imports.

**Comment by hendrikebbers** [comment]
@vil02 I assigned you to the issue :)

**Comment by vil02** [comment]
@hendrikebbers: these imports were removed in #29 by @Ariho-Seth...
