### ISSUE TITLE
Create a repositors for transactions

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/hedera-enterprise#39]
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to this project or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3AOpenElements+archived%3Afalse+label%3A%22good+first+issue%22) is to help you make your first contribution.

## 👾 Description of the issue

The code already cotains the `com.openelements.hedera.base.NftRepository` interface that acts as a rapper around REST calls against a [Mirror Node](https://docs.hedera.com/hedera/core-concepts/mirror-nodes). Here only some specific of the REST endpoints that are provided by a Mirror Node are used. A full documentation of the REST API can be found [here](https://docs.hedera.com/hedera/sdks-and-apis/rest-api). Next to that Hedera provides a Swagger UI for specific mirror nodes. The Swagger UI for the Mirror Node of the Hedera testnet can be found [here](https://testnet.mirrornode.hedera.com/api/v1/docs/#/).

As you can see in the documentation and Swagger UI the Mirror Node expose a lot of information. Some of this information is specific to transactions and for that an `TransactionRepository` interface should be defined that is similar to the `NftRepository`. 

Next to the interface definition an implementation (see `NftRepositoryImpl` class for reference) and unit tests must be created.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. 
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** to your branch
- [ ] **Start a Pull Request (PR)**: in the hedera-enterprise repository
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the community for support.
- [ ] **Wait for reviews:** Members of the community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of our community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional informantion

If you have any questions, just ask us directly in this issue by adding a comment. You can join the Hedera community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by belloibrahv** [comment]
> Request to Work on the Issue:
> 
> 
> Hi, I’m interested in working on this issue as part of Hacktoberfest. I’ve reviewed the details and am looking forward to helping define and implement the `TransactionRepository` interface.
> 
> **Summary of My Understanding:**
> The project currently includes an `NftRepository` interface that interacts with specific REST endpoints from the Mirror Node API. The goal of this issue is to create a similar `TransactionRepository` interface, implement it, and write unit tests to ensure correct functionality.
> 
> **Clarification Questions:**
> 
> 1. Should the `TransactionRepository` handle all transaction-related REST endpoints, or are there specific endpoints that should be prioritized?
> 2. What are the key transaction details (e.g., transaction ID, timestamp) that the `TransactionRepository` should focus on retrieving?
> 3. Are there existing unit tests for the `NftRepository` that we can reference when creating tests for `TransactionRepository`?
> 4. Should we include error handling for failed transactions or network issues similar to the `NftRepository`?
> 5. Is there a preferred method for testing the API endpoints during development (e.g., using Swagger UI for the Mirror Node)?
> 
> Thanks for your time! I’m excited to start working on this once I’m officially assigned to the issue.

**Comment by belloibrahv** [comment]
@hendrikebbers could you please assign this issue for me to work on? thank you.

**Comment by belloibrahv** [comment]
🚀

**Comment by belloibrahv** [comment]
Kindly help in reviewing my PR when you are free #61
