### ISSUE TITLE
Create version 0.10 by hand

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/hedera-enterprise#69]
As you can see at https://github.com/OpenElements/hedera-enterprise/releases/tag/v0.11.0 the version v0.10.0 has never been created at GitHub. That is related to https://github.com/OpenElements/hedera-enterprise/issues/68

We should create v0.10.0 by hand and move all changes up to the creation of v0.10.0 from the v0.11.0 change log to v0.10.0

**Comment by Ndacyayisenga-droid** [comment]
@hendrikebbers  fixed [here](https://github.com/OpenElements/hedera-enterprise/releases)
